### ISSUE TITLE
arch Linux distro Became slow to respond after building banan-os 

### ISSUE THREAD

**Issue by almezali** [Bananymous/banan-os#2]
my computer Became slow to respond after building banan-os 

https://github.com/Bananymous/banan-os

I build the toolchain for this os"arch Linux"

./bos toolchain

I want to repair my system 

my computer Became slow to respond

Pls Tell me the steps to solve the problem The system is responding slower

**Comment by Bananymous** [comment]
You already closed the issue, but I can still provide a solution.

System becomes slow because `./bos toolchain` by default uses all logical threads for the compilation. This is done so compilation will be done as fast as possible. You can limit the number of threads used with `MAKE_JOBS` environment variable.

For example
```bash
MAKE_JOBS=-j4 ./bos toolchain
```
will only use 4 threads for the compilation.

If you want to make the system more responsive straight away, you can just kill the toolchain compilation process (ctrl+c).

**Comment by almezali** [comment]
I have already done it By building banan-os
Successfully 
then Storage unit only 1 GB left 
I deleted the folder. banan-os
•
my computer Became slow to respond

Pls Tell me the steps to solve the problem The system is responding slower
.
I want to repair my system

**Comment by almezali** [comment]
banan-os already built in my arch Linux 
I want to remove it
and repair my system

**Comment by Bananymous** [comment]
banan-os build system is fully contained within the directory you cloned it to. So removing the directory will free up all of the disk space used by banan-os. If removing this directory and maybe rebooting the system does not bring the system back to normal performance, I'm afraid it has nothing to banan-os. If your disk is really having only 1 GB of free space that can explain the slowness (from filesystem).

I would recommend clearing up space from the disk and checking what is using system resources with `top`, `htop`, or whatever system monitor you are using.

**Comment by Dcraftbg** [comment]
Remove the folder and clean the disk. It's more than likely not an issue with banan-os however and either you have way too little storage or there's some process thats eating up a lot of your CPU.
